# Generated by Django 3.2.20 on 2023-07-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230727_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
